spring:
  application:
    name: fraud-intelligence-service

  datasource:
    url: jdbc:postgresql://localhost:5433/fraud_ai
    username: postgres
    password: postgres

  jpa:
    open-in-view: false

    show-sql: true

    properties:
      hibernate:
        format_sql: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${app.kafka.fraud-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    bootstrap-servers: localhost:9092
app:
  kafka:
    fraud-case-topic: fraud-case-events
    fraud-group: fraud-intelligence-group



server:
  port: 8080

ollama:
  base-url: http://localhost:11434
  embedding-model: nomic-embed-text